name: Generate 3D Contrib

on:
  # 每天自动运行一次 (UTC时间 00:00，即北京时间早上8点)
  schedule:
    - cron: "0 0 * * *"
  # 允许手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v3

      # 2. 运行生成脚本
      - uses: ryo-ma/github-profile-3d-contrib@v0.8.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 直接复制这一行，不用改！
          USERNAME: "bingege-0729" # 这里填你的用户名

      # 3. 提交生成的图片到你的仓库
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "generated" || exit 0
          git push
