name: Generate 3D Contrib

on:
  # 每天自动运行一次
  schedule:
    - cron: "0 0 * * *"
  # 允许手动触发
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 生成 3D 图 (这里修复了 Token 传递问题)
      - name: Generate 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: "bingege-0729"

      # 3. 提交图片
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          # 如果没有变化，git commit 会报错，所以用 || exit 0 忽略错误
          git commit -m "chore: update 3d contrib" || exit 0
          git push
